#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Biokemijska informatika  # The title of the book. Will be placed in the left navbar.
author                      : Miha Pavšič  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo
repository:
  url                       : https://github.com/mpavsic/biokeminfo
html:
  use_repository_button     : true
launch_buttons:
  binderhub_url             : https://mybinder.org