# Book settings
title: Biokemijska informatika
author: Miha Pavšič
copyright: "2024"
logo: logo.png
exclude_patterns: [_build, .DS_Store, "*resitev.ipynb", "*resitev.md"]
only_build_toc_files: false

# Information about where the book exists on the web
repository:
  url: https://github.com/mpavsic/biokeminfo
  path_to_book: biokeminfo
  branch: main

# Customizations
html:
  favicon: favicon.ico
  use_edit_page_button: false
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar: true
  use_multitoc_numbering: false
  extra_navbar: ""
  extra_footer: ""
  baseurl: https://mpavsic.github.io/biokeminfo
  google_analytics_id: G-KG7KWKX5VG
launch_buttons:
  binderhub_url: https://mybinder.org
  notebook_interface: jupyterlab
  colab_url: https://colab.research.google.com