#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Biokemijska informatika  # The title of the book. Will be placed in the left navbar.
author                      : Miha Pavšič  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo
exclude_patterns            : [_build, .DS_Store, "*resitev.ipynb", "*resitev.md"]
repository:
  url                       : https://github.com/mpavsic/biokeminfo
  path_to_book              : biokeminfo
  branch                    : main
html:
  favicon                   : https://raw.githubusercontent.com/mpavsic/biokeminfo/main/biokeminfo/favicon.ico
  use_repository_button     : true
  use_edit_page_button      : false
  use_issues_button         : false
  extra_navbar              : ""
  extra_footer              : ""
  baseurl                   : https://mpavsic.github.io/biokeminfo
  home_page_in_navbar       : true
  google_analytics_id       : G-KG7KWKX5VG
launch_buttons:
  binderhub_url             : https://mybinder.org
  notebook_interface        : jupyterlab
  colab_url                 : https://colab.research.google.com